### ISSUE TITLE
Live preview is not working

### ISSUE THREAD

**Issue by Pils19** [neeleshbisht99/Saral-interface#3]
I tried to have a look at the live preview, but the page remains blank.
I used the following link:
https://neeleshbisht99.github.io/Saral-interface/

I got the following error message from javascript console:

`Uncaught TypeError: Cannot read property 'apply' of undefined
    at redux.js:600
    at s (redux.js:79)
    at Module.179 (index.jsx:25)
    at a ((index):1)
    at Object.87 (main.400b2247.chunk.js:1)
    at a ((index):1)
    at t ((index):1)
    at Array.r [as push] ((index):1)
    at main.400b2247.chunk.js:1`

**Comment by neeleshbisht99** [comment]
Redux tools extension dependency  in production was not removed earlier, fixed that with custom compose function for redux store. Thanks for the bug, application working fine now
